### ISSUE TITLE
IO-Socket-Async-SSL-0.7.4 installation fails on Windows

### ISSUE THREAD

**Issue by wahnwitz** [jnthn/p6-io-socket-async-ssl#46] opened 2019-11-01 09:28 UTC
```
:\Users\Administrator.DOTZON-SERVER.000\.zef\store\IO-Socket-Async-SSL-0.7.4.tar.gz>zef install C:\Users\Administrator.DOTZON-SERVER.000\.zef\store\IO-Socket-Async-SSL-0.7.4.tar.gz\IO-Socket-Async-SSL
===> Testing: IO::Socket::Async::SSL:ver<0.7.4>
Unhandled exception in code scheduled on thread 4
Cannot resolve caller quit(Supplier::Preserving:U: X::AdHoc:D); none of these signatures match:
    (Supplier:D: Exception $ex, *%_)
    (Supplier:D: $message, *%_)
  in block  at C:\Users\Administrator.DOTZON-SERVER.000\.zef\store\IO-Socket-Async-SSL_1572600106\IO-Socket-Async-SSL_1572600
106\lib\IO\Socket\Async\SSL.pm6 (IO::Socket::Async::SSL) line 256

===> Testing [FAIL]: IO::Socket::Async::SSL:ver<0.7.4>
Aborting due to test failure: IO::Socket::Async::SSL:ver<0.7.4> (use --force-test to override)
```

Installation(testing) of package fails on Windows Server and Windows7 too.

**Comment by coke** [comment] 2019-11-01 13:30
I get the same error on my windows install (run from my home dir rather than inside .zef store...)

```
>perl6 --version
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.
>zef --version
v0.7.1
>zef install IO::Socket::Async::SSL
===> Searching for: IO::Socket::Async::SSL
===> Testing: IO::Socket::Async::SSL:ver<0.7.4>
Unhandled exception in code scheduled on thread 4
Cannot resolve caller quit(Supplier::Preserving:U: X::AdHoc:D); none of these signatures match:
    (Supplier:D: Exception $ex, *%_)
    (Supplier:D: $message, *%_)
<snip>
```

**Comment by raiph** [comment] 2019-11-01 20:10
This looks like a dupe of #42.

**Comment by jnthn** [comment] 2019-11-02 13:27
Finally got to try it out on a Windows box, to figure out which test is to blame. Turns out only one of them fail:

```
C:\consulting\perl6\p6-io-socket-async-ssl>prove -e "perl6 -Ilib" t
t\bad-incoming.t ... ok
t\ciphers.t ........ ok
t\client-server.t .. ok
t\dh-ciphers.t ..... ok
t\ecdh-ciphers.t ... ok
t\encoding.t ....... ok
t\thread-stress.t .. ok
t\upgrade.t ........ Unhandled exception in code scheduled on thread 4
Cannot resolve caller quit(Supplier::Preserving:U: X::AdHoc:D); none of these si
gnatures match:
    (Supplier:D: Exception $ex, *%_)
    (Supplier:D: $message, *%_)
  in block  at C:\consulting\perl6\p6-io-socket-async-ssl\lib\IO\Socket\Async\SS
L.pm6 (IO::Socket::Async::SSL) line 254

t\upgrade.t ........ Dubious, test returned 1 (wstat 256, 0x100)
No subtests run

Test Summary Report
-------------------
t\upgrade.t      (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=8, Tests=31, 52 wallclock secs ( 0.03 usr +  0.06 sys =  0.09 CPU)
Result: FAIL
```

**Comment by jnthn** [comment] 2019-11-02 13:46
49a12a4971765 fixes that exception, however just gets us onto another problem:

```
ok 1 - Got expected upgrade response
MoarVM panic: use of invalid eventloop work item index -1
```

**Comment by jnthn** [comment] 2019-11-02 14:38
And 72e27486852c7 seems to fix that test on Windows, and it still passes on Linux.

**Comment by jnthn** [comment] 2019-11-02 15:00
Releaed 0.7.5 with the fixes.

**Closed by jnthn** 2019-11-02 15:00 UTC
